version: "3.8"
services:
    # Run-container-mounted does this:
    # containerName=${1:-projector-idea-c}
    # docker run --rm -p 8887:8887 -v ~/projector-docker:/home/projector-user -it "$containerName"
    ide:
        image: registry.jetbrains.team/p/prj/containers/projector-idea-u
        ports:
            - 8887:8887
        volumes:
            - $HOME/projector-user:/home/projector-user
            - /d:/d
